services:
  db:
    image: postgres:15
    container_name: campusvoice-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: campusvoice
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: campusvoice-web-1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data: